### ISSUE TITLE
Krack attacks

### ISSUE THREAD

**Issue by pparent76** [adde88/hostapd-mana#2]
Hi,

Thanks a lot for your work!

Did you apply Patches against Krack attacks on this one?

Pierre.

**Comment by adde88** [comment]
I'm not sure if the Krack patches have been applied to this version (2.6) of hostapd.
Considering this is NOT to be used as your regular AP, but rather as an attack, fooling people into connecting. I cannot really see any issues with not having said patches installed.
Feel free to re-open the issue if you see this as an actual issue. :)
